"C:\Users\seyou\.jdks\temurin-21.0.8\bin\jpackage.exe" ^
  --name xsd_generator ^
  --app-version 1.0 ^
  --input build\libs ^
  --main-jar xsd_generator-1.0.jar ^
  --main-class MainFrame ^
  --type exe ^
  --win-shortcut ^
  --win-menu ^
  --win-dir-chooser ^
  --dest dist ^
  --verbose